apisetu:
  endpoint:
    findByPin: https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=#pin#&date=#date#
    findByPinMulti: https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode=#pin#&date=#date#
cron:
  expression: 0 0,30 7-23 ? * *
  
server:
  port: 5000
spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
#    url: jdbc:postgresql://postgres.c6uec03u1bpm.ap-south-1.rds.amazonaws.com:5432/postgres
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      max_allowed_packet: 2000
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: vacslot.alert@gmail.com
    password: Vacslot@123
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          port: 25
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
    mainSub: "Vaccine slots is available on #date#"
    multiMailSub: "Vaccine slots are available at your pincode : #pin#"
    regSub: Registration is successful
#swagger:
#  utl: http://localhost:8080/swagger-ui/
vaccine:
  mail:
    notification: templates/vaccine.vm
    registration: templates/registration.vm
    frequency: 7
app:
   api:
      password: V@c$l0t_P@$$word
      sevenDaysAvailabilityOn: true   